version: '3.9'

services:
  app:
    image: ghcr.io/ibrahim4529/todo-action-server:latest
    env_file:
      - .env
    command: 
      - uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4 

  nginx:
    image: ghcr.io/ibrahim4529/todo-action-nginx:latest
    ports:
      - 80:80
      - 443:443