version: '3.9'

services:
  app:
    build: 
      context: .
      dockerfile: ./deployment/app/Dockerfile
    env_file:
      - .env

  nginx:
    build: 
      context: .
      dockerfile: ./deployment/nginx/Dockerfile
    ports:
      - 80:80
      - 443:443